django_poll/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),

]

polls/urls.py
from django.urls import path

from . import views, api_views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('polls/<int:pk>', views.IndexDetailView.as_view(), name='question_list'),
    path('polls/<int:pk>/results', views.vote, name='results'),

    # API

    path('login/', api_views.login, name='login'),
    # poll
    path('poll/create/', api_views.poll_create, name='poll_create'),
    path('poll/update/<int:poll_id>/', api_views.poll_update, name='poll_update'),
    path('poll/view/', api_views.polls_view, name='polls_view'),
    path('poll/view/active/', api_views.active_polls_view, name='active_poll_view'),
    # question
    path('question/create/', api_views.question_create, name='question_create'),
    path('question/update/<int:question_id>/', api_views.question_update, name='question_update'),
    # choice
    path('choice/create/', api_views.choice_create, name='choice_create'),
    path('choice/update/<int:choice_id>/', api_views.choice_update, name='choice_update'),
    # answer
    path('answer/create/', api_views.answer_create, name='answer_create'),
    path('answer/view/<int:user_id>/', api_views.answer_view, name='answer_view'),
    path('answer/update/<int:answer_id>/', api_views.answer_update, name='answer_update'),
]

polls/models.py
import datetime
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class Poll(models.Model):

    poll_name = models.CharField('название опроса', max_length=200)
    date_start = models.DateTimeField('начало')
    date_end = models.DateTimeField('окончание')
    description = models.TextField('Описание')

    def __str__(self):
        return self.poll_name


class Question(models.Model):
    TEXT = 'text'
    ONCE = 'radio'
    MULTI = 'checkbox'

    choices = (
        (TEXT, 'Text'),
        (ONCE, 'radiobutton'),
        (MULTI, 'checkbox'),
    )

    poll = models.ForeignKey(Poll, on_delete=models.CASCADE,
                             null=True, blank=True)
    question_text = models.CharField(max_length=200,
                                     verbose_name='название вопроса')
    question_type = models.CharField(max_length=20, verbose_name='тип вопроса',
                                     choices=choices, default=TEXT)

    def __str__(self):
        return self.question_text


class Choice(models.Model):

    choice_question = models.ForeignKey(Question, on_delete=models.CASCADE,
                                        null=True, blank=True)
    choice_text = models.CharField(max_length=200,
                                   verbose_name='Вариант ответа')
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Answer(models.Model):
    user_id = models.IntegerField()
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE, null=True)
    choice_text = models.CharField(max_length=200)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question, Poll


class IndexView(generic.ListView):
    model = Poll
    template_name = 'polls/index.html'
    context_object_name = 'polls_list'

    def get_queryset(self):
        return Poll.objects.order_by('id')


class IndexDetailView(generic.DetailView):

    model = Poll
    template_name = 'polls/polls_detail.html'
    context_object_name = 'polls'

    def get_queryset(self):
        return Poll.objects.all()


class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'
    context_object_name = 'res'

    def get_queryset(self):
        return Poll.objects.all()

polls/templates/polls/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
      {% block title %}
        Опросник
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/sketchy/bootstrap.min.css" integrity="sha384-RxqHG2ilm4r6aFRpGmBbGTjsqwfqHOKy1ArsMhHusnRO47jcGqpIQqlQK/kmGy9R" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'polls:index' %}">Polls</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'polls:index' %}">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:polls_view' %}">Api</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    <div class="container mt-5">
      <div class="row">
        <div class="col-6 offset-md-2">
          {% block content %}
            Now no content
          {% endblock %}
        </div>
      </div>
    </div>



  </body>
</html>

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block title %}
  Список опросов
{% endblock %}


{% block content %}
  <h1 class="mb-5">Опросы:</h1>
  {% if polls_list %}
    {% for poll in polls_list %}
      <div class="card mb-5">
        <h5 class="card-header">{{ poll.date_start }} - {{ poll.date_end }}</h5>
        <div class="card-body">
          <h5 class="card-title">{{ poll.poll_name }}</h5>
          <p class="card-text">{{ poll.description }}</p>
          <a href="{% url 'polls:question_list' poll.id %}" class="btn btn-primary">Пройти опрос</a>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <p>Опросов не найдено</p>
  {% endif %}
{% endblock %}

polls/templates/polls/polls_detail.html
{% extends 'polls/base.html' %}

{% block title %}
  {{ polls.poll_name }}
{% endblock %}

{% block content %}

<h1 class="mb-5">{{ polls.poll_name }}</h1>


<form action="{% url 'polls:results' polls.id %}" method="post">
{% csrf_token %}
{% for question in polls.question_set.all %}
  <h2 class="mt-5 mb-5">{{ question.question_text }}</h2>
  {% for choice in question.choice_set.all %}
    <input type="{{ question.question_type }}" name="choice" id="choice{{ forloop.counter }}" value="" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
  {% endfor %}
{% endfor %}
<br />
<input type="submit" value="Отправить" />
</form>
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block title %}
  {{ poll.poll_name }}
{% endblock %}


{% block content %}
<h1>{{ question.question_text }}</h1>
<h1>{{ poll.poll_name }}</h1>


{% for question in poll.question_set.all %}
  <h2 class="mt-5 mb-5">{{ question.question_text }}</h2>
  <ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
  </ul>
{% endfor %}


<button type="button" class="btn btn-success">
  <a href="{% url 'polls:index' %}">Вернуться на главную</a>
</button>

{% endblock %}